### PR TITLE
Add Personal page

### PR DESCRIPTION
**Pull request by dtnwen**

### CODE REVIEW

**Review by technophile-04 — APPROVED** [review]
Hey thanks @dtnwen ! 

Screenshot 2024-01-21 at 5 05 02 PM

Nice use of `Address` component !! , It looks like you didn't buy ENS name, or did you for other address ?  If you didn't get the scholarship to buy ENS name please feel free text it on Batch 1 TG group chat 🙌

**Comment by dtnwen** [comment]
@technophile-04 Hey, ty! I didn't get the scholarship actually. I ask in the group chat but no one answered(

**Comment by carletex** [comment]
>> @technophile-04 Hey, ty! I didn't get the scholarship actually. I ask in the group chat but no one answered(

@dtnwen let me work on that.

**Comment by dtnwen** [comment]
> >> @technophile-04 Hey, ty! I didn't get the scholarship actually. I ask in the group chat but no one answered(
> 
> 
> 
> @dtnwen let me work on that.

Appreciate that!

**Comment by carletex** [comment]
@dtnwen done! https://etherscan.io/tx/0xf9f1d38f375a2515301df871f097bc4f00a3de3f2dfaa15959ac582585ac6732

**Comment by dtnwen** [comment]
> @dtnwen done! https://etherscan.io/tx/0xf9f1d38f375a2515301df871f097bc4f00a3de3f2dfaa15959ac582585ac6732

@carletex ty! I will get an ens right away

**Pull request merged**
